### ISSUE TITLE
Two versions of jQuery in two locations on base.html

### ISSUE THREAD

**Issue by TrishZwei** [nighthawkcoders/flask-idea-homesite#6]
jQuery version 3.1.1 is found in the head of the base html document and jQuery version 3.2.1 is found in the bottom of the document. Current version of jQuery is 3.5.1 and its full tag (with integrity and crossorign attributes) can be found on https://code.jquery.com/ this code should probably be updated and put in only one location. Can be put in the head and deferred or at the bottom so that it loads after the DOM.

Bootstrap 4 apparently is looking to use the slim (rather than full) version, which eliminates some of jQ's functionality (animation and ajax for example). My recommendation is to use the full version for ease of implementation. Being aware that there are two versions is something to take into consideration when looking at why things may break at certain points when working with student's code in their projects.

**Comment by nathanielCherian** [comment]
Good Call

**Comment by nathanielCherian** [comment]
[fix](https://github.com/nighthawkcoders/flask-idea-homesite/commit/e65e79b9290444e58537c406bca31f5c10ee4dce)
